/*
 * This source file was generated by the Gradle 'init' task
 */
package me.nax.examples.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HelloWorldTest {
    @Test void appHasAGreeting() {
        HelloWorld classUnderTest = new HelloWorld();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
